# Generated by Django 6.1 on 2026-08-17 17:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('daily_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), max_digits=8)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EarningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('display_asset', models.CharField(default='BTC/USDT', max_length=30)),
                ('display_direction', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=10)),
                ('display_entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('display_take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('display_stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('earning_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), max_digits=8)),
                ('earning_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PARTICIPATED', 'Participated'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20)),
                ('participated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earning_sessions', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earning_sessions', to='investments.investment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
