# Generated by Django 6.1 on 2026-08-21 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_date', models.DateField()),
                ('slot', models.CharField(choices=[('MORNING', '10:00 AM'), ('EVENING', '9:00 PM')], max_length=10)),
                ('scheduled_at', models.DateTimeField()),
                ('pair', models.CharField(default='BTC/USDT', max_length=30)),
                ('direction', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=10)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], default='PUBLISHED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='investment',
            name='duration_days',
            field=models.PositiveIntegerField(default=35),
        ),
        migrations.AddConstraint(
            model_name='earningsession',
            constraint=models.UniqueConstraint(fields=('investment', 'session_date'), name='one_daily_payout_per_investment'),
        ),
        migrations.AddConstraint(
            model_name='signal',
            constraint=models.UniqueConstraint(fields=('signal_date', 'slot'), name='unique_signal_slot_per_day'),
        ),
        migrations.AddField(
            model_name='signalparticipation',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_participations', to='investments.investment'),
        ),
        migrations.AddField(
            model_name='signalparticipation',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='investments.signal'),
        ),
        migrations.AddField(
            model_name='signalparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='signalparticipation',
            constraint=models.UniqueConstraint(fields=('user', 'investment', 'signal'), name='one_participation_per_signal_investment'),
        ),
        migrations.AddConstraint(
            model_name='signalparticipation',
            constraint=models.CheckConstraint(condition=models.Q(('investment__isnull', False)), name='participation_has_investment'),
        ),
    ]
