# Generated by Django 6.1 on 2026-08-22 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_signal_signalparticipation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='earningsession',
            name='one_daily_payout_per_investment',
        ),
        migrations.AddField(
            model_name='earningsession',
            name='signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earning_sessions', to='investments.signal'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='slot',
            field=models.CharField(choices=[('MORNING', '10:00 AM'), ('AFTERNOON', '3:00 PM'), ('EVENING', '9:00 PM')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='earningsession',
            constraint=models.UniqueConstraint(fields=('investment', 'signal'), name='one_payout_per_investment_signal'),
        ),
    ]
