# Generated by Django 6.1 on 2026-08-22 10:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_remove_earningsession_one_daily_payout_per_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningsession',
            name='payout_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsession',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='profit_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0100'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='earningsession',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('TRADED', 'Traded'), ('MISSED', 'Missed'), ('SETTLED', 'Settled')], default='AVAILABLE', max_length=20),
        ),
    ]
