# Generated by Django 6.0.4 on 2026-08-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_earningsession_payout_due_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningsession',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ACTIVE', 'Active'), ('TRADED', 'Traded'), ('MISSED', 'Missed'), ('SETTLED', 'Settled')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='signal',
            name='slot',
            field=models.CharField(choices=[('MORNING', '5:00 PM'), ('AFTERNOON', '7:00 PM'), ('EVENING', '8:00 PM (Team Leader)')], max_length=10),
        ),
    ]
