# Generated by Django 6.0.4 on 2026-08-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_alter_earningsession_status_alter_signal_slot'),
        ('wallet', '0003_platformconfiguration_withdrawalnetwork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='deposit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment', to='wallet.cryptodeposit'),
        ),
    ]
