# Generated by Django 6.0.4 on 2026-08-25 16:19

from django.db import migrations, models
import secrets


def backfill_account_ids(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    used = set(User.objects.exclude(account_id__isnull=True).exclude(account_id='').values_list('account_id', flat=True))
    for user in User.objects.filter(account_id__isnull=True) | User.objects.filter(account_id=''):
        while True:
            account_id = f"CDD-{secrets.randbelow(900000) + 100000}"
            if account_id not in used:
                used.add(account_id)
                user.account_id = account_id
                user.save(update_fields=['account_id'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_id',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill_account_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(blank=True, editable=False, max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_network',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
