# Generated by Django 6.1 on 2026-08-25 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_account_id_user_withdrawal_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiditWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('webhook_type', models.CharField(max_length=100)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('AWAITING_USER', 'Awaiting user'), ('IN_REVIEW', 'In review'), ('VERIFIED', 'Verified'), ('DECLINED', 'Declined'), ('RESUBMITTED', 'Resubmitted'), ('ABANDONED', 'Abandoned'), ('EXPIRED', 'Expired'), ('KYC_EXPIRED', 'KYC expired')], default='NOT_STARTED', max_length=24)),
                ('didit_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('vendor_data', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
