# Generated by Django 6.0.2 on 2026-09-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_totp_authenticator_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverificationcode',
            name='accounts_ev_user_id_7aa99a_idx',
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('login', 'Sign in'), ('password_reset', 'Password reset')], default='login', max_length=24),
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['user', 'purpose', 'used_at', 'expires_at'], name='accounts_ev_usrprp_98d2c1_idx'),
        ),
    ]
