# Generated by Django 6.1 on 2026-08-22 09:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='earning_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0200'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='membership',
            name='daily_sessions',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('TEAM_LEADER', 'Team Leader')], default='REGULAR', max_length=20),
        ),
    ]
