# Generated by Django 6.1 on 2026-08-22 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(default='USDT', max_length=12)),
                ('network', models.CharField(default='TRC20', max_length=20)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(default='USDT', max_length=12)),
                ('network', models.CharField(default='TRC20', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMING', 'Confirming'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verification_note', models.TextField(blank=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_deposits', to=settings.AUTH_USER_MODEL)),
                ('deposit_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='wallet.depositaddress')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnRampOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=20)),
                ('estimated_usdt', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('provider_reference', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SETTLED', 'Settled'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='INITIATED', max_length=20)),
                ('checkout_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onramp_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='depositaddress',
            constraint=models.UniqueConstraint(fields=('user', 'asset', 'network'), name='one_active_deposit_address_per_network'),
        ),
    ]
