# Generated by Django 6.0.4 on 2026-08-25 16:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_depositaddress_cryptodeposit_onramporder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_deposit', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=20)),
                ('deposit_asset', models.CharField(default='USDT', max_length=12)),
                ('deposit_network', models.CharField(default='TRC20', max_length=32)),
                ('deposit_address', models.CharField(default='TLsHkop8XAc5dafJUAEEaQ9MMBNptnr1Vf', max_length=255)),
                ('principal_lock_days', models.PositiveIntegerField(default=39)),
                ('signal_window_minutes', models.PositiveIntegerField(default=15)),
                ('settlement_minutes', models.PositiveIntegerField(default=45)),
                ('team_leader_requirement', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='deposit_proofs/'),
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='receiving_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cryptodeposit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMING', 'Confirming'), ('COMPLETED', 'Completed'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('asset', models.CharField(default='USDT', max_length=12)),
                ('address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
