# Generated by Django 6.1 on 2026-09-27
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("wallet", "0007_platformconfiguration_signal_window_30_minutes")]
    operations = [migrations.CreateModel(name="MpesaDeposit", fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("amount_kes", models.DecimalField(decimal_places=2, max_digits=12)),
        ("phone_number", models.CharField(max_length=15)),
        ("checkout_request_id", models.CharField(max_length=128, unique=True)),
        ("merchant_request_id", models.CharField(blank=True, max_length=128)),
        ("receipt_number", models.CharField(blank=True, max_length=64)),
        ("result_code", models.IntegerField(blank=True, null=True)),
        ("result_description", models.CharField(blank=True, max_length=255)),
        ("callback_payload", models.JSONField(blank=True, default=dict)),
        ("status", models.CharField(choices=[("PENDING", "Pending"), ("PAID", "Paid"), ("FAILED", "Failed")], default="PENDING", max_length=12)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mpesa_deposits", to=settings.AUTH_USER_MODEL)),
    ], options={"ordering": ["-created_at"]})]